/**
  ******************************************************************************
  *
  * @Module: Port
  * @FileName: Port_PBcfg.c
  * @Description: Post Build Configuration Source file for Port Module.
  * @version: 1.0.0
  * @date:    xx-xx-2020
  * @Authors: Ahmed Mohsen  && Ahmed Khamis && Ashraf Amgad
  *
  * @Brief: this file contains:
  *                     (1) Module version along with AUTOSAR version,
  *                     (2) Version checking between "Port_PBcfg.c" and "Port.h" files
  *                     (3) Post Build Configration Structure.
  * @Reminder: (Post = After)
  ******************************************************************************
  */

#include "Port.h"

/*
 * Module Version 1.0.0
 */

#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
#error "The SW version of PBcfg.c does not match the expected version"
#endif



/* Post Build (PB) structure used with Port_Init API */
/**< it is a structure of the type "Port_ConfigType " which is defined in "Port.h".
        this structure is also used (passed to) ???
        this type of variable is const i order not to be Altered from another file but this one.
        the below structure contains the desired (user preference) setting about each pin in Our micro-controller:
                PORTx
                PINx
                Pin Direction initial value
                Pin Level initial value ??
                Pin Mode initial value (ADC, Timers. etc)
                Pin driven mode initial value (Pull-up, floating, etc)
                */
const Port_ConfigType Port_Configuration =
{
    PORT_A_NUM, PORT_PIN_0_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_1_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_2_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_3_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_4_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_5_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_6_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_7_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_8_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_9_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_10_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_11_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_12_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_A_NUM, PORT_PIN_15_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,

    PORT_B_NUM, PORT_PIN_0_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_1_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,   
   	PORT_B_NUM, PORT_PIN_3_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_4_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_5_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_6_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_7_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_8_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_9_NUM, PORT_PIN_DIRECTION_INITIAL_VALUE, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_10_NUM, PORT_PIN_OUT, STD_HIGH, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_11_NUM, PORT_PIN_OUT, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_12_NUM, PORT_PIN_OUT, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_13_NUM, PORT_PIN_OUT, STD_HIGH, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_14_NUM, PORT_PIN_OUT, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_B_NUM, PORT_PIN_15_NUM, PORT_PIN_OUT, PORT_PINLEVEL_INITIAL_VALUE, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,

    PORT_C_NUM, PORT_PIN_13_NUM, PORT_PIN_OUT, STD_LOW, PORT_PIN_MODE_INITIAL_VALUE, GPIO_Push_Pull,
    PORT_C_NUM, PORT_PIN_14_NUM, PORT_PIN_OUT, STD_HIGH, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE,
    PORT_C_NUM, PORT_PIN_15_NUM, PORT_PIN_OUT, STD_HIGH, PORT_PIN_MODE_INITIAL_VALUE, PORT_PIN_DRIVEN_MODE_INITIAL_VALUE

};
